package tse.cargauy.exceptions;

public enum CodigoError {

    EMPRESA_NRO_INVALIDO(1001, Categoria.VALIDACION),
    EMPRESA_NOMBRE_PUBLICO_REQUERIDO(1002, Categoria.VALIDACION),
    EMPRESA_RAZON_SOCIAL_REQUERIDA(1003, Categoria.VALIDACION),
    EMPRESA_NRO_DUPLICADO(1004, Categoria.CONFLICTO),
    EMPRESA_NO_ENCONTRADA(1005, Categoria.NO_ENCONTRADO),

    VEHICULO_MATRICULA_REQUERIDA(2001, Categoria.VALIDACION),
    VEHICULO_MARCA_REQUERIDA(2002, Categoria.VALIDACION),
    VEHICULO_PESO_INVALIDO(2003, Categoria.VALIDACION),
    VEHICULO_CAPACIDAD_INVALIDA(2004, Categoria.VALIDACION),
    VEHICULO_EMPRESA_REQUERIDA(2005, Categoria.VALIDACION),
    VEHICULO_MATRICULA_DUPLICADA(2006, Categoria.CONFLICTO),
    VEHICULO_NO_ENCONTRADO(2007, Categoria.NO_ENCONTRADO),

    PERMISO_NRO_REQUERIDO(3001, Categoria.VALIDACION),
    PERMISO_PERIODO_REQUERIDO(3002, Categoria.VALIDACION),
    PERMISO_RANGO_FECHAS_INVALIDO(3003, Categoria.VALIDACION),
    PERMISO_VEHICULO_REQUERIDO(3004, Categoria.VALIDACION),
    PERMISO_NRO_DUPLICADO(3005, Categoria.CONFLICTO),
    PERMISO_SUPERPUESTO(3006, Categoria.CONFLICTO),

    GUIA_FECHA_REQUERIDA(5002, Categoria.VALIDACION),
    GUIA_ORIGEN_REQUERIDO(5003, Categoria.VALIDACION),
    GUIA_DESTINO_REQUERIDO(5004, Categoria.VALIDACION),
    GUIA_ORIGEN_IGUAL_DESTINO(5018, Categoria.VALIDACION),
    GUIA_VOLUMEN_INVALIDO(5005, Categoria.VALIDACION),
    GUIA_EMPRESA_REQUERIDA(5006, Categoria.VALIDACION),
    GUIA_RUBRO_REQUERIDO(5007, Categoria.VALIDACION),
    GUIA_TIPO_CARGA_REQUERIDO(5008, Categoria.VALIDACION),
    GUIA_RESPONSABLE_INVALIDO(5009, Categoria.VALIDACION),
    GUIA_NO_ENCONTRADA(5011, Categoria.NO_ENCONTRADO),
    GUIA_NO_MODIFICABLE(5012, Categoria.CONFLICTO),
    GUIA_CON_VIAJE(5013, Categoria.CONFLICTO),
    GUIA_ASIGNADA_DATOS_FIJOS(5019, Categoria.CONFLICTO),
    RUBRO_NO_ENCONTRADO(5014, Categoria.NO_ENCONTRADO),
    TIPO_CARGA_NO_ENCONTRADO(5015, Categoria.NO_ENCONTRADO),

    VIAJE_GUIA_REQUERIDA(6001, Categoria.VALIDACION),
    VIAJE_VEHICULO_REQUERIDO(6002, Categoria.VALIDACION),
    VIAJE_CHOFER_REQUERIDO(6003, Categoria.VALIDACION),
    VIAJE_NO_ENCONTRADO(6004, Categoria.NO_ENCONTRADO),
    VIAJE_GUIA_YA_ASIGNADA(6005, Categoria.CONFLICTO),
    VIAJE_VEHICULO_OTRA_EMPRESA(6006, Categoria.VALIDACION),
    VIAJE_CHOFER_INVALIDO(6007, Categoria.VALIDACION),
    VIAJE_CAPACIDAD_EXCEDIDA(6008, Categoria.VALIDACION),
    VIAJE_VEHICULO_SIN_PERMISO(6009, Categoria.VALIDACION),
    VIAJE_NO_MODIFICABLE(6010, Categoria.CONFLICTO),

    USUARIO_CEDULA_REQUERIDA(4001, Categoria.VALIDACION),
    AUTH_SOLICITUD_INVALIDA(4002, Categoria.NO_AUTENTICADO),
    AUTH_TOKEN_INVALIDO(4003, Categoria.NO_AUTENTICADO),
    AUTH_PROVEEDOR_NO_DISPONIBLE(4004, Categoria.NO_DISPONIBLE),
    AUTH_CLIENTE_NO_CONFIGURADO(4005, Categoria.CONFIGURACION),
    AUTH_SESION_INVALIDA(4006, Categoria.NO_AUTENTICADO),
    AUTH_SECRETO_NO_CONFIGURADO(4007, Categoria.CONFIGURACION),
    AUTH_SECRETO_CORTO(4008, Categoria.CONFIGURACION),

    NODO_IDENTIFICADOR_REQUERIDO(7001, Categoria.VALIDACION),
    NODO_TIPO_REQUERIDO(7002, Categoria.VALIDACION),
    NODO_IDENTIFICADOR_DUPLICADO(7003, Categoria.CONFLICTO),
    NODO_NO_ENCONTRADO(7004, Categoria.NO_ENCONTRADO),
    NODO_DADO_DE_BAJA(7005, Categoria.CONFLICTO),

    PAGINACION_INVALIDA(8001, Categoria.VALIDACION),
    PARAMETRO_INVALIDO(8002, Categoria.VALIDACION),
    ACCESO_DENEGADO(8003, Categoria.PROHIBIDO);

    private final int codigo;
    private final Categoria categoria;

    CodigoError(int codigo, Categoria categoria) {
        this.codigo = codigo;
        this.categoria = categoria;
    }

    public int getCodigo() {
        return codigo;
    }

    public Categoria getCategoria() {
        return categoria;
    }
}
